import unittest
from src import needleman_wunsch, smith_waterman

class TestAlignmentAlgorithms(unittest.TestCase):
    # Setup method to initialize parameters before each test
    def setUp(self):
        self.seq1 = "ATAT"
        self.seq2 = "TATA"
        self.substitution_matrix_path = "substitution_matrix.csv"  
        self.gap_penalty = -2
        self.max_alignments = 2
        self.output_file = "output.txt"

    # Test the Needleman-Wunsch algorithm
    def test_needleman_wunsch(self):
        score, alignments = needleman_wunsch(self.seq1, self.seq2, self.substitution_matrix_path, self.gap_penalty, self.max_alignments, self.output_file)
        self.assertIsNotNone(score, "Score should not be None")
        self.assertGreaterEqual(len(alignments), 1, "At least one alignment should be returned")
        self.assertTrue(all("-" in alignment or alignment.replace("-", "") in self.seq1 + self.seq2 for alignment in alignments), "Alignments should contain valid characters")


    # Test the Smith-Waterman algorithm
    def test_smith_waterman(self):
        score, alignments = smith_waterman(self.seq1, self.seq2, self.substitution_matrix_path, self.gap_penalty, self.max_alignments, self.output_file)
        self.assertIsNotNone(score, "Score should not be None")
        self.assertGreaterEqual(len(alignments), 1, "At least one alignment should be returned")
        self.assertTrue(all("-" in alignment or alignment.replace("-", "") in self.seq1 + self.seq2 for alignment in alignments), "Alignments should contain valid characters")

     # Test the content of the output file generated by the Needleman-Wunsch function
    def test_output_file(self):
        needleman_wunsch(self.seq1, self.seq2, self.substitution_matrix_path, self.gap_penalty, self.max_alignments, self.output_file)
        with open(self.output_file, "r") as file:
            output_content = file.read()
        self.assertIn("Global alignment no.", output_content, "Output file should contain alignment headers")
        self.assertIn("Score:", output_content, "Output file should contain scores for each alignment")

if __name__ == "__main__":
    unittest.main()
